services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_PROVIDER: sqlite
      DATABASE_PATH: /data/order-demo.db
    ports:
      - "3000:3000"
    volumes:
      - nest_data:/data

volumes:
  nest_data:
